<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="images/favicon.ico" type="image/ico" />

        <title>AfriqueStock</title>

        <!-- Bootstrap -->
        <link href="<?= $this->url->getBaseUri(); ?>public/adm/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Bootstrap -->
        <link href="<?= $this->url->getBaseUri(); ?>public/adm/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?= $this->url->getBaseUri(); ?>public/adm/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?= $this->url->getBaseUri(); ?>public/adm/vendors/nprogress/nprogress.css" rel="stylesheet">
        <link rel="shortcut icon" href="<?= $this->url->getBaseUri(); ?>public/images/icone/africone.png">
        <!-- Custom Theme Style -->

        <!--<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">-->
        <link href="<?= $this->url->getBaseUri(); ?>public/adm/build/css/custom.min.css" rel="stylesheet">
        <!--<link href="<?= $this->url->getBaseUri(); ?>public/adm//css/bootstrap.min.css" rel="stylesheet">-->
        <link href="<?= $this->url->getBaseUri(); ?>public/adm/ncss/styles.css" rel="stylesheet">
        <link href="<?= $this->url->getBaseUri(); ?>public/adm/css/image.css" rel="stylesheet">


    </head>

    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="#" class="site_title"><i class="fa fa-paw"></i> <span>AfriqueStock</span></a>
                        </div>

                        <div class="clearfix"></div>

                        <!-- menu profile quick info -->
                        <div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Welcome,</span>
                                <h2>John Doe</h2>
                            </div>
                        </div>
                        <!-- /menu profile quick info -->

                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">
                                <h3>General</h3>
                                <ul class="nav side-menu">
                                    <li><a href="#"><i class="fa fa-home"></i> Dashboard</a>
                                        
                                    </li>
                                    <li><a href="<?= $this->url->get("admin/categorie/") ?>"><i class="fa fa-edit"></i> Gestions des cat&eacute;gories</a>
                                        <!--                                        <ul class="nav child_menu">
                                                                                    <li><a href="#">General Form</a></li>
                                                                                    <li><a href="form_advanced.html">Advanced Components</a></li>
                                                                                    <li><a href="form_validation.html">Form Validation</a></li>
                                                                                    <li><a href="form_wizards.html">Form Wizard</a></li>
                                                                                    <li><a href="form_upload.html">Form Upload</a></li>
                                                                                    <li><a href="form_buttons.html">Form Buttons</a></li>
                                                                                </ul>-->
                                    </li>
                                    <li><a><i class="fa fa-desktop"></i> Gestions des clients <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="<?= $this->url->get("admin/client/abonne") ?>">abonn&eacute;e</a></li>
                                            <li><a href="<?= $this->url->get("admin/client/contributeur") ?>">contributeur</a></li>
                                            <li><a href="<?= $this->url->get("admin/client/photographe") ?>">photographe</a></li>
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-table"></i> Gestions des images <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="<?= $this->url->get("admin/image/newPicture") ?>">ajouter</a></li>
                                            <li><a href="<?= $this->url->get("admin/image/allPicture") ?>">les images</a></li>
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-bar-chart-o"></i> Gestions abonnements <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="<?= $this->url->get("admin/abonnement/formule") ?>">Cr&eacute;er un abonnements</a></li>
                                            <li><a href="#">nos abonnées</a></li>
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-clone"></i>Gestions des factures <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="#">Fixed Sidebar</a></li>
                                            <li><a href="#">Fixed Footer</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <div class="menu_section">
                                <h3>Syst&egrave;me</h3>
                                <ul class="nav side-menu">
                                    <li><a><i class="fa fa-bug"></i> Gestions profils <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="#">nouveau</a></li>
                                            <li><a href="#">listes</a></li>
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-windows"></i> Gestion utilisateurs <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="#">nouveau</a></li>
                                            <li><a href="#">listes</a></li>

                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-sitemap"></i>Configuration <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="#">syst&egrave;me</a></li>
                                            <li><a href="#">syst&egrave;me</a></li>     
                                        </ul>
                                    </li>                  
                                    <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">documentation</span></a></li>
                                </ul>
                            </div>

                        </div>
                        <!-- /sidebar menu -->

                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small">
                            <a data-toggle="tooltip" data-placement="top" title="Settings">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Lock">
                                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </div>
                        <!-- /menu footer buttons -->
                    </div>
                </div>

                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <nav>
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>

                            <ul class="nav navbar-nav navbar-right">
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <img src="images/img.jpg" alt="">John Doe
                                        <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        <li><a href="javascript:;"> Profile</a></li>
                                        <li>
                                            <a href="javascript:;">
                                                <span class="badge bg-red pull-right">50%</span>
                                                <span>Settings</span>
                                            </a>
                                        </li>
                                        <li><a href="javascript:;">Help</a></li>
                                        <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                    </ul>
                                </li>

                                <li role="presentation" class="dropdown">
                                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fa fa-envelope-o"></i>
                                        <span class="badge bg-green">6</span>
                                    </a>
                                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                        <li>
                                            <a>
                                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a>
                                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a>
                                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a>
                                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <div class="text-center">
                                                <a>
                                                    <strong>See All Alerts</strong>
                                                    <i class="fa fa-angle-right"></i>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- /top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">
                    <?= $this->getContent(); ?>
                </div>
                <!-- /page content -->

                <!-- footer content -->
                <footer>
                    <div class="pull-right">
                        afriquestock r&eacute;alis&eacute; par l&apos;&eacute;quipe <a href="https://colorlib.com">TJ-Tech</a>
                    </div>
                    <div class="clearfix"></div>
                </footer>
            </div>
        </div>

        <!-- jQuery -->
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendors/nprogress/nprogress.js"></script>
        <!-- jQuery Smart Wizard -->
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendors/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>
        <!-- Custom Theme Scripts -->
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/build/js/custom.min.js"></script>
        <script src="<?= $this->url->getBaseUri(); ?>public/adm/build/js/delete.js"></script>
        <!-- the fileinput plugin initialization -->
        <script>
            var btnCust = '<button type="button" class="btn btn-secondary" title="Add picture tags" ' +
                    'onclick="alert(\'Call your custom code here.\')">' +
                    '<i class="glyphicon glyphicon-tag"></i>' +
                    '</button>';
            $("#avatar-1").fileinput({
                overwriteInitial: true,
                maxFileSize: 1500,
                showClose: false,
                showCaption: false,
                browseLabel: '',
                removeLabel: '',
                browseIcon: '<i class="glyphicon glyphicon-folder-open"></i>',
                removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
                removeTitle: 'Cancel or reset changes',
                elErrorContainer: '#kv-avatar-errors-1',
                msgErrorClass: 'alert alert-block alert-danger',
                defaultPreviewContent: '<img src="/uploads/default_avatar_male.jpg" alt="Your Avatar">',
                layoutTemplates: {main2: '{preview} ' + btnCust + ' {remove} {browse}'},
                allowedFileExtensions: ["jpg", "png", "gif"]
            });
        </script>
     
<!--        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>-->
        <script>
            $(document).ready(function () {
                $('#example').DataTable();
            });
        </script>




    </body>
</html>
