<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>AfriqueStock</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="<?= $this->url->getBaseUri(); ?>public/adm/vendor/iconfonts/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="<?= $this->url->getBaseUri(); ?>public/adm/vendor/iconfonts/puse-icons-feather/feather.css">
  <link rel="stylesheet" href="<?= $this->url->getBaseUri(); ?>public/adm/vendor/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="<?= $this->url->getBaseUri(); ?>public/adm/vendor/css/vendor.bundle.addons.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="<?= $this->url->getBaseUri(); ?>public/adm/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="<?= $this->url->getBaseUri(); ?>public/adm/images/favicon.png" />
  <link rel="shortcut icon" href="<?= $this->url->getBaseUri(); ?>public/images/icone/africone.png">
</head>

<body>
    <?= $this->getContent(); ?>
</body>
  <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendor/js/vendor.bundle.base.js"></script>
  <script src="<?= $this->url->getBaseUri(); ?>public/adm/vendor/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="<?= $this->url->getBaseUri(); ?>public/adm/js/off-canvas.js"></script>
  <script src="<?= $this->url->getBaseUri(); ?>public/adm/js/hoverable-collapse.js"></script>
  <script src="<?= $this->url->getBaseUri(); ?>public/adm/js/misc.js"></script>
  <script src="<?= $this->url->getBaseUri(); ?>public/adm/js/settings.js"></script>
  <script src="<?= $this->url->getBaseUri(); ?>public/adm/js/todolist.js"></script>

</html>