<div class="container">
    <div class="row">
        <div class="col-md-3" style=" height: auto;">&nbsp;</div>
        <div class="col-md-6">
            <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <?php echo $this->flashSession->output() ?>
                <div class="col-md-12 row notification alert fade in alert-dismissable" >
                    <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
                    <p><?php echo $this->flashSession->output() ?></p>
                </div>
            <?php endif; ?>

            <div class="clearfix">&nbsp;</div>
            <div class="clearfix">&nbsp;</div>

            <div class="col-md-12 ">
                <form method="post" action="<?= $this->url->get("contributor/index"); ?>">
                    <div class="form-group" align="center">
                        <h4> Rejoigner la communaut&eacute; et commencer &agrave; vendre d&egrave;s la premi&egrave;re seconde</h4>
                    </div>
                    <div class="form-group">
                        <label for="name"> Nom comptet </label>
                        <input type="text" class="form-control" name="nom"  required="" placeholder="Nom" value="<?= (isset($nom) ? $nom : "") ?>" />
                    </div>
                    <div class="form-group">
                        <label for="name"> Pseudo </label>
                        <input type="text" class="form-control" name="prenom" required=""  placeholder="Prenom" value="<?= (isset($prenom) ? $prenom : "") ?>" />
                    </div>
                    <div class="form-group">
                        <label for="name"> Email </label>
                        <input type="email" class="form-control" id="Email" name="email" required="" placeholder="Email" value="<?= (isset($email) ? $email : "") ?>" />
                    </div>

                    <div class="form-group">
                        <label for="name2"> Mot de passe </label>
                        <input type="password" class="form-control" name="password"  id="inputPassword4" placeholder="Password" required="">
                    </div>
                    <div class="form-group">
                        <label for="name2"> Confirmer </label>
                        <input type="password" class="form-control" name="confirmer"  id="inputPassword4" placeholder="Password" required="">
                    </div>


                    <div class="row">
                        <span class="col-md-12">
                            <button type="submit" class="btn btn-secondary btn-lg btn-block connect">Connexion</button>
                        </span>
                        <span class="clearfix">&nbsp;</span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="clearfix">&nbsp;</div>