<?php
if (!isset($pays)) {
    $pays = [];
}
?>


<div class="container">
    <form method="post" action="<?= $this->url->get("contributor/adresse") ?>">
        <div>&nbsp;</div>
        <div class="col-md-3" style=" height: auto;">&nbsp;</div>
        <div class="row">
            <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
                <div class="col-md-12 row notification alert fade in alert-dismissable" >
                    <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
                    <p><?= $this->flashSession->output() ?></p>
                </div>
            <?php endif; ?>
        </div>
        <div>&nbsp;</div>


        <div class="row col-md-12">
            <div class="col-md-6">
                <div class="form-group text-default">
                    <h4>Adresse du domicile</h4>
                </div>
                <div class="form-group">
                    <label for="name">Pays</label>
                    <select class="form-control" name="pays">
                        <?php foreach ($pays as $country): ?>
                            <option value="<?= $country->id ?>"><?= $country->nompays ?></option>
                        <?php endforeach; ?>

                    </select>
                </div>
                <div class="form-group">
                    <label for="name"> Ville </label>
                    <input type="text" class="form-control" name="ville"  placeholder="ville" value="<?= (isset($ville) ? $ville : "") ?>" />
                </div>
                <div class="form-group">
                    <label for="name"> Region </label>
                    <input type="text" class="form-control" id="region" name="region" placeholder="region" value="<?= (isset($region) ? $region : "") ?>" />
                </div>

                <div class="form-group">
                    <label for="name2"> Boîte Postal </label>
                    <input type="text" class="form-control" name="boitePostal"  id="inputPassword4" placeholder="Boite postal" />
                </div>

                <div class="form-group">
                    <label for="name2"> Num&eacute;ro </label>
                    <input type="text" class="form-control" name="numero"  id="inputPassword4" placeholder="Numero" />
                </div>

            </div>
            <div class="col-md-6">

                <div class="form-group text-default">
                    <h4>Adresse du domicile</h4>
                </div>

                <!--                <form>-->
                <div class="form-group">
                    <label for="name"> Pays </label>
                    <select class="form-control" name="pays2">
                        <?php foreach ($pays as $country): ?>
                            <option value="<?= $country->id ?>"><?= $country->nompays ?></option>
                        <?php endforeach; ?>

                    </select>
                </div>

                <div class="form-group">
                    <label for="ville">Ville</label>
                    <input type="text" class="form-control" name="ville2"  placeholder="ville" value=""/>
                </div>

                <div class="form-group">
                    <label for="name"> Region </label>
                    <input type="text" class="form-control" id="Email" name="region2" placeholder="region" value="<?= (isset($email) ? $email : "") ?>" />
                </div>

                <div class="form-group">
                    <label for="name2">Boite Postal</label>
                    <input type="text" class="form-control" name="boitePostal2"  id="inputPassword4" placeholder="Boîte postale" />
                </div>
                <!--                </form>-->


            </div>
        </div>
        <div class="clearfix">&nbsp;</div>
        <div class="row">
            <span class="col-md-4">&nbsp;</span>
            <span class="col-md-push-4 col-md-4 col-md-pull-4">
                <button type="submit" class="btn btn-secondary btn-lg btn-block connect">Suivant</button>
            </span>
        </div>
    </form>
</div>
<div class="clearfix">&nbsp;</div>

