

<div class="section">
    <div class="container">
        <div class="row">
            <div class="clearfix">&nbsp;</div>
            <div class="container Div-Entete">
                <div class="grid_12">
                    <h3 class="text-center">Commencer à se servir de notre site est très simple</h3>
                    <p align="justify"><a>Ouvrez un compte Contributeur:</a> absolument gratuitement et sans obligations;puis Transférer vos fichiers pour les mettre en vente sur le site.(Tous les fichiers que vous envoyez sont vérifiés par nos vérificateurs, et lorsque l'inspection est passée, ils apparaissent sur le site. À cet instant ils sont disponibles pour les Acheteurs, et peuvent commencer à vous rapporter !)</p>
                </div>
            </div>




            <div class="container div-blockA">    
                <div class="grid_12">

                    <div class="titre">
                        <h4 class="text-center">LES CONDITIONS POUR METRE VOS OEUVRES EN LIGNE</h4>
                    </div>

                    <div class="Div-modaliter">
                        <p align="justify">En acceptant les modalités et conditions de <a href="">l'Accord de Fourniture</a> que vous acceptez en créant un compte de Contributeur, et en transférant vos fichiers sur notre site, vous garantissez que : Vous êtes l'auteur de tous les fichiers que vous transférez, vous avez 18 ans ou plus, et vous possédez tous les documents et droits requis vous permettant de montrer et d'utiliser vos fichiers ainsi que tous les éléments associés (autorisation du modèle, du propriétaire, etc.;</p>
                    </div>

                </div>
            </div>




            <div class="container div-ExigenceT">
                <div class="grid_12">              
                    <h2>EXIGENCE POUR LES FICHIERS</h2> 
                </div>
            </div>

            <div class="container D-vgarD">
                <div class="grid_12 div-Exigence">                
                    <div class="row">
                        <div class="grid_2 Div-exiIMG">
                            <img src="<?php echo $this->url->getBaseUri() . "public/images/designe elemt/photo.png" ?>" class="img-responsive img-P">
                        </div>
                        <div class="grid_10 Div-cont">
                            <h4>Exigences pour les photos:</h4>
                            <p>Les photos doivent être au format JPEG/JPG ou au format PNG avec un espace de couleur RGB; <br> <br>
                                La résolution minimale est<strong> 3,8 Mpx (2400 x 1600);</strong> <br> <br>
                                Les photos ne doivent pas dépasser 50 Mo et ne doivent pas etres inferieur a 5 Mo.
                            </p>

                        </div>
                    </div>
                </div>
            </div>






            <div class="clearfix">&nbsp;</div>


            <div class="container D-vgarD">
                <div class="grid_12 div-Exigence">      
                    <div class="row">

                        <div class="grid_2 Div-exiIMG">
                            <img src="<?php echo $this->url->getBaseUri() . "public/images/designe elemt/vecteur-ico.png" ?>" class="img-responsive img-P">
                        </div>

                        <div class="grid_10 Div-cont">
                            <h4>Exigences pour les vecteurs :</h4>
                            <p>Les formats d'image vectorielle acceptés : AI et EPS; <br> <br>
                                Les images vectorielles doivent être dans une archive ZIP accompagnées d'un aperçu en JPG/JPEG. La résolution minimale de l'aperçu JPG/JPEG est 3,8 Mpx (2400 x 1600);<br><br>
                                Les archives ZIP ne doivent pas dépasser 50 Mo.
                            </p>
                        </div>

                    </div>
                </div>
            </div>
            <div class="clearfix">&nbsp;</div>
            <!--  PSD -->
            <div class="container D-vgarD">
                <div class="grid_12 div-Exigence">      
                    <div class="row">

                        <div class="grid_2 Div-exiIMG">
                            <img src="<?php echo $this->url->getBaseUri() . "public/images/designe elemt/photoshop.png" ?>" class="img-responsive img-P">
                        </div>

                        <div class="grid_10 Div-cont">
                            <h4>Exigences pour Création en PSD :</h4>
                            <p>Les formats acceptés : PSD; <br> <br>
                                Les Créations d'images doivent être dans une archive ZIP accompagnées d'un aperçu en JPG/JPEG ou PNG. La résolution minimale de l'aperçu JPG/JPEG ou PNG est 3,8 Mpx (2400 x 1600);<br> <br>
                                Les archives ZIP ne doivent pas dépasser 50 Mo.
                            </p>
                        </div>

                    </div>
                </div>
            </div>
            <div class="clearfix">&nbsp;</div>
            <!--  Video -->
            <div class="container D-vgarD">
                <div class="grid_12 div-Exigence">      

                    <div class="row">

                        <div class="grid_2 Div-exiIMG">
                            <img src="<?php echo $this->url->getBaseUri() . "public/images/designe elemt/Video.png" ?>" class="img-responsive img-P">
                        </div>

                        <div class="grid_10 Div-cont">
                            <h4>Exigences pour les vidéos :</h4>
                            <p>Les formats acceptés : ASF, AVI, DV, FLV, MOV, MPEG/MPG, WMV; <br> <br>

                                les codecs acceptés : Photo JPEG, Motion JPEG-A/B; DV, HDV, DVCPro; H.264/AVC, DivX, Xvid, SVQ1, MP42, MP43, MPG4, MP4V, M4S2, MPEG-1, MPEG-2; WMV2, WMV3; FLV;<br> <br>

                                Les archives ZIP ne doivent pas dépasser 50 Mo. <br> <br>

                                Le FPS doit correspondre au format vidéo (norme NTSC 29,97 FPS ou PAL à 25 FPS). Nous acceptons 23.976, 24, 25, 29.97, 30, 50, 59.93 ou 60 FPS (images/seconde) ;<br> <br>

                                La résolution minimale est 0,07 Mpx (320 x 240 pixels). La résolution maximale n'est pas limitée ;<br> <br>

                                La durée minimum d'une séquence vidéo est de 5 secondes. La durée maximum d'une séquence vidéo est de 60 secondes.<br> <br>

                                Le niveau de compression doit correspondre à la meilleure qualité d'image possible;<br> <br>

                                Le son peut être accepté s'il fait partie de la scène (ambiance sonore, voix). Les vidéos ne doivent pas contenir d'enregistrement audio qui ne soit pas la 
                                propriété du Contributeur de la vidéo;<br> <br>

                                La taille de fichier maximale pour une vidéo est de 2048 Mo.

                            </p>
                        </div>

                    </div>
                </div>
            </div>
            
            <div class="clearfix">&nbsp;</div>

            <!-- Contributeur --> 

            <div class="container div-ExigenceT">     
                <div class="grid_12">                
                    <h2>LES CONTRIBUTEURS</h2>
                </div>
            </div>

            <div class="container D-vgarD">
                <div class="grid_12 div-Exigence">      
                    <div class="row">

                        <div class="grid_2 Div-exiIMG">
                            <img src="<?php echo $this->url->getBaseUri() . "public/images/designe elemt/contributeur.png" ?>" class="img-responsive img-P">
                        </div>

                        <div class="grid_10 Div-cont">

                            <p>tous nos contributeurs gagnent 30% sur chaque image vendue sur une durée illimitée. Les calculs de redevance ne sont pas basés sur une valeur "standard" d'un fichier, 
                                mais sur le montant effectivement payé par un acheteur. Si un acheteur bénéficie d'une réduction à l'achat, la redevance perçue par le contributeur pour le fichier sera 
                                établie d'après le montant payé par l'acheteur, en prenant en compte la réduction et pas la valeur "normale" du fichier.
                                <!-- les contributeurs sont rembouser a chaque fois qu'il ateind le montant minimum de 100$
                                -->                      </p>

                        </div>

                    </div>
                </div>
            </div>
            <div class="clearfix">&nbsp;</div>


        </div>
    </div>
</div>


<div class="clearfix">&nbsp; </div>
<div class="container">
    <div class="grid_12 text-center div-commencer">
        <a href="<?= $this->url->get('account/contributor/'); ?>"><button type="button" class="btn btn-primary btn-Commencer">Commencer maintenant</button></a>
    </div>
</div>
<div class="clearfix">&nbsp; </div>