<?php
if (!isset($panier)) {
    $panier = [];
}
$total = 0;
?>
<div class="container">
    <div class="clearfix">&nbsp;</div>


    <table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:50%">Product</th>
                <th style="width:10%">Price</th>
                <th style="width:8%">Quantity</th>
                <th style="width:22%" class="text-center">Subtotal ($)</th>
                <th style="width:10%">Total (XOF)</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($panier as $achat): ?>
                <tr>
                    <td data-th="Product">
                        <div class="row">
                            <div class="col-sm-2 hidden-xs"><img src="<?php echo $this->url->getBaseUri() . "public/images/photo/" . $achat->images->affiche; ?>" alt="..." class="img-responsive"/></div>
                            <div class="col-sm-10">
                                <h4 class="nomargin">Product 1</h4>
                                <p><?= $achat->images->description ?></p>
                                <p>Taille: <?= $achat->taille ?></p>
                                
                            </div>
                        </div>
                    </td>
                    <td data-th="Price"><?= $achat->totalvente ?></td>
                    <td data-th="Quantity">
                        <input type="test" class="form-control text-center" value="1" readonly="yes">
                    </td>
                    <td data-th="Subtotal ($)" class="text-center"><?= $achat->totalvente ?></td>
                    <td data-th="Total (XOF)" class="text-center">
                        <?= ($achat->totalvente)* 550 ?>
                        <!--<a href="<?php // $this->url->get("shopping/drop?code=" . $achat->idpanier . '_' . $achat->idproduit) ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>-->								
                    </td>
                </tr>
                <?php
                $total += $achat->totalvente;
            endforeach;
            ?>
        </tbody>
        <tfoot>
            <tr class="visible-xs">
                <td class="text-center"><strong>Total <?= $total ?></strong></td>
            </tr>
            <tr>
                <td><a href="<?= $this->url->get("images/freepicture") ?>" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
                <td colspan="2" class="hidden-xs"></td>
                <td class="hidden-xs text-center"><strong>Total <?= $total ?>$</strong></td>
                <td>
                <?php if($total >0): ?>

                    <!--src="https://checkout.fedapay.com/js/checkout.js"-->
                    <!--data-public-key="pk_live_wEykyHglqqVjpcy7NeeFZpgG"-->
                    <form action="<?= $this->url->get("shopping/transaction") ?>" method="POST">
                        <script
                            src="https://sandbox-checkout.fedapay.com/js/checkout.js"
                            data-public-key="pk_sandbox_L835B89pVn0IE8lpZe0Istpj"
                            data-button-text="Payer: <?= ($total * 550) ?> XOF"
                            data-button-class="button-class btn btn-sm"
                            data-transaction-amount="<?= ($total * 550) ?>"
                            data-transaction-description="Description de la transaction"
                            data-currency-iso="XOF"
                            data-widget-description="Votre boutique 100% africaine"
                            data-widget-image="https://live-checkout.fedapay.com/img/marketplace.svg"
                            data-widget-title="AfriqueStock">
                        </script>

                        <input type="hidden" value="<?= $total ?>" name="montant"> 
                        <?php foreach ($panier as $achat): ?>
                        <input type="hidden" class="form-control text-center" value="<?= $achat->idproduit ?>" name="produit[]">
                        <input type="hidden" class="form-control text-center" value="<?= $achat->taille ?>" name="taille[]">
                        <input type="hidden" class="form-control text-center" value="<?= $achat->totalvente ?>" name="prix[]">
                        <?php  endforeach; ?>
                    </form>
                    <?php endif; ?>
                </td>

            </tr>
        </tfoot>
    </table>

    <div class="clearfix">&nbsp;</div>




</div>