<main>
    <section class="well center">
        <div class="container">
            <div class="row">
                <form method="post" action="<?= $this->url->get("account/contributor"); ?>">
                    <div class="grid_12">
                        <div class="wraper-cnt wow fadeInLeft">
                            <div class="limiter">
                                <div class="container-login100">
                                    <div class="grid_12 wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                                        <div class="login100-form validate-form flex-sb flex-w">
                                            <span class="login100-form-title p-b-32">
                                                Adresse Domicile
                                            </span>
                                            <span class="txt1 p-b-11">
                                                Pays
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                                                <select class="input100" type="text" name="pays" required="">
                                                    <option value="1">BENIN</option>
                                                </select>
                                                <span class="focus-input100"></span>
                                            </div>

                                            <span class="txt1 p-b-11">
                                                Ville
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                                <input class="input100" type="text" name="ville" required="">
                                                <span class="focus-input100"></span>
                                            </div>

                                            <span class="txt1 p-b-11">
                                                Region
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                                <input class="input100" type="text" name="region" required="">
                                                <span class="focus-input100"></span>
                                            </div>

                                            <span class="txt1 p-b-11">
                                                Boite Postal
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-12" data-validate = "boite postal is required">
                                                <input class="input100" type="text" name="boitePostale" required="">
                                                <span class="focus-input100"></span>
                                            </div>
                                            <span class="txt1 p-b-11">
                                                Telephone
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-12" data-validate = "telephone is required">
                                                <input class="input100" type="text" name="telephone" required="">
                                                <span class="focus-input100"></span>
                                            </div>

                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="grid_12">
                        <div class="wraper-cnt wow fadeInLeft">
                            <div class="limiter">
                                <div class="container-login100">
                                    <div class="grid_12 wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                                        <div class="login100-form validate-form flex-sb flex-w">
                                            <span class="login100-form-title p-b-32">
                                                Adresse bureau
                                            </span>
                                            <span class="txt1 p-b-11">
                                                Pays
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                                                <select class="input100" type="text" name="paysB" >
                                                    <option value="1">BENIN</option>
                                                </select>
                                                <span class="focus-input100"></span>
                                            </div>

                                            <span class="txt1 p-b-11">
                                                Ville
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                                <input class="input100" type="text" name="villeB" >
                                                <span class="focus-input100"></span>
                                            </div>

                                            <span class="txt1 p-b-11">
                                                Region
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                                <input class="input100" type="text" name="regionB" >
                                                <span class="focus-input100"></span>
                                            </div>

                                            <span class="txt1 p-b-11">
                                                Boite Postal
                                            </span>
                                            <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                                <input class="input100" type="text" name="boitePostaleB" >
                                                <span class="focus-input100"></span>
                                            </div>

                                            <div class="container-login100-form-btn">
                                                <button class="login100-form-btn" type="submit">
                                                    Subscribe
                                                </button>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </section>
</main>>

