<main>
    <section class="well center">
        <div class="container">
            <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
                <div class="col-md-12 row notification alert fade in alert-dismissable" >
                    <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
                    <p><?php $this->flashSession->output() ?></p>
                </div>
            <?php endif; ?>
            <div class="row">
                <div class="grid_3">
                    &nbsp;
                </div>

                <div class="grid_6">
                    <div class="wraper-cnt wow fadeInLeft">
                        <div class="limiter">
                            <div class="container-login100">
                                <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                                    <form class="login100-form validate-form flex-sb flex-w" method="post" action="<?= $this->url->get("account/create") ?>">
                                        <span class="login100-form-title p-b-32">
                                            Create New Account
                                        </span>

                                        <span class="txt1 p-b-11">
                                            Nom
                                        </span>
                                        <div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                                            <input class="input100" type="text" name="nom" required="">
                                            <span class="focus-input100"></span>
                                        </div>

                                        <span class="txt1 p-b-11">
                                            Prenom
                                        </span>
                                        <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
<!--                                                        <span class="btn-show-pass">
                                                <i class="fa fa-eye"></i>
                                            </span>-->
                                            <input class="input100" type="text" name="prenom" required="">
                                            <span class="focus-input100"></span>
                                        </div>
                                        <span class="txt1 p-b-11">
                                            Email
                                        </span>
                                        <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
<!--                                                        <span class="btn-show-pass">
                                                <i class="fa fa-eye"></i>
                                            </span>-->
                                            <input class="input100" type="email" name="email" required="">
                                            <span class="focus-input100"></span>
                                        </div>
                                        <span class="txt1 p-b-11">
                                            Password
                                        </span>
                                        <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                            <span class="btn-show-pass">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                            <input class="input100" name="pass" type="password" required="">
                                            <span class="focus-input100"></span>
                                        </div>
                                        <span class="txt1 p-b-11">
                                            Confirm
                                        </span>
                                        <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                            <span class="btn-show-pass">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                            <input class="input100" name="confirm" type="password" required="">
                                            <span class="focus-input100"></span>
                                        </div>



                                        <div class="container-login100-form-btn">
                                            <button class="login100-form-btn" type="submit">
                                                Create
                                            </button>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="grid_3">
                    &nbsp;
                </div>

            </div>

        </div>
    </section>
    <hr>

</main>