<?php
//$this->assets->outputCss(); 
if (!isset($page)) {
    $page = [];
}
if (!isset($images)) {
    $images = [];
}
if (!isset($categories)) {
    $categories = [];
}

?>



<div class="main-container" data-viewManager data-pagination data-lightboxes-modal  data-accountsform data-validation >
    <div class="body-content" >

        <input id="shouldShowOverlayExperiment" value="false" type="hidden" />
        <input id="shouldShowModalExperiment" value="false" type="hidden" />
        <input id="isFiniteScrollEnabled" value="false" type="hidden" />


        <div class="search-results container search-common js_search_results ">

            <input type="hidden" data-identifier="search-options-string" value="{&quot;searchterm&quot;:&quot;femme&quot;,&quot;image_type&quot;:&quot;all&quot;,&quot;search_source&quot;:&quot;base_search_form&quot;,&quot;language&quot;:&quot;fr&quot;}" />


            <div class="search-content">
                <ul class="search-results-grid js_search-results-grid mosaic-grid js_mosaic js_responsive">
                    <?php foreach ($page->items as $image): ?>
                        <li class="li js_item" data-width="450" data-height="318" data-aspect="<?= ($image->width / $image->height) ?>">
                            <div class="img-wrap">
                                <img src="<?php echo $this->url->getBaseUri() . "public/images/photo/" . $image->affiche; ?>" alt="Beautiful african american girl with an afro hairstyle smiling" width="390" height="280">
                            </div>

                            <div class="overlay">



                                <a href="<?= $this->url->get("images/details?id=" . $image->idimage); ?>" class="js_related-item a" data-current-order-index=""  data-track="click.searchResults.image-1-720115051" >
                                    <div class="data-track"  data-track="click.searchResults.image" >
<!--                                        <div class="description">
                                            Beautiful african american girl with an afro hairstyle smiling
                                        </div>-->
                                    </div>
                                </a>

                                <div class="actions js_actions">
                                    <div class="actions-row">
                                        <button
                                            data-href="/fr/editor/image/720115051"
                                            rel="nofollow"
                                            target="_blank"
                                            data-track="click.searchResults.openEditor"

                                            class="btn btn-icon editor-icon-link i-editor i-toggle"
                                            data-title="Ouvrir dans l'Éditeur"
                                            >
                                            <i class="sstk-icon icon-system-editor"></i>
                                        </button>
                                    </div>

                                    <div class="actions-row">
                                        <button data-href="/g/contributor/999518?searchterm=femme"
                                                class="btn btn-icon i-more-artist i-toggle"
                                                data-title="Voir d’autres éléments de cet artiste"
                                                data-track="click.searchResults.moreFromArtist"
                                                >
                                            <i class="sstk-icon icon-artist"></i>
                                        </button>
                                    </div>

                                    <div class="actions-row">

                                        <button data-href="/fr/search/similar/720115051"
                                                class="btn btn-icon i-similar i-toggle"

                                                data-title="Voir les images similaires"

                                                data-track="click.searchResults.searchSimilar"
                                                >
                                            <i class="sstk-icon icon-similar"></i>
                                        </button>
                                    </div>
                                    <div class="actions-row">
                                        <button class="btn btn-icon i-lightbox js_lightbox_add"
                                                data-id="720115051"
                                                data-title="Enregistrer dans une collection"
                                                data-lightboximageid="720115051"
                                                data-toggle="modal"
                                                data-target=".lightbox-modal"
                                                data-track="click.searchResults.saveToLightboxModal"
                                                >
                                            <i class="sstk-icon icon-plus-sign"></i>
                                        </button><button class="btn btn-icon i-menu">
                                            <i class="sstk-icon icon-more"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>










                </ul>

            </div>
            <div class="clearfix">&nbsp;</div>
            <?php if (sizeof($page->items) > 100): ?>
                <div class="col-md-12">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item"><a class="page-link" href="<?= $this->url->get("images/freepicture"); ?>">First</a></li>
                            <li class="page-item"><a class="page-link" href="<?= $this->url->get("images/freepicture?page=$page->before"); ?>">Previous</a></li>
                            <li class="page-item"><a class="page-link" href="<?= $this->url->get("images/freepicture?page=$page->next"); ?>">Next</a></li>
                            <li class="page-item"><a class="page-link" href="<?= $this->url->get("images/freepicture?page=$page->last"); ?>">Last</a></li>
                            <span  class="text-warning" style="padding: 5px;">&nbsp;<?php echo "You are in page ", $page->current, " of ", $page->total_pages; ?></span>
                        </ul>
                    </nav>
                </div>
            <?php endif; ?>


        </div>
    </div>
</div>

<!--/div-->
