
<section class="well center">
    <div class="container">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div class="col-md-12 row notification alert fade in alert-dismissable" >
                <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
                <p><?php $this->flashSession->output() ?></p>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="grid_3">
                &nbsp;
            </div>

            <div class="grid_6">
                <div class="wraper-cnt wow fadeInLeft">
                    <div class="limiter">
                        <div class="container-login100">
                            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                                <form class="login100-form validate-form flex-sb flex-w" method="post" action="<?= $this->url->get("account/login") ?>">
                                    <span class="login100-form-title p-b-32">
                                        Account Login
                                    </span>

                                    <span class="txt1 p-b-11">
                                        Username
                                    </span>
                                    <div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                                        <input class="input100" type="text" name="username" >
                                        <span class="focus-input100"></span>
                                    </div>

                                    <span class="txt1 p-b-11">
                                        Password
                                    </span>
                                    <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
                                        <span class="btn-show-pass">
                                            <i class="fa fa-eye"></i>
                                        </span>
                                        <input class="input100" type="password" name="password" >
                                        <span class="focus-input100"></span>
                                    </div>

                                    <div class="flex-sb-m w-full p-b-48">
                                        <div class="contact100-form-checkbox">
                                            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                                            <label class="label-checkbox100" for="ckb1">
                                                Remember me
                                            </label>
                                        </div>

                                        <div>
                                            <a href="#" class="txt3">
                                                Forgot Password?
                                            </a>
                                        </div>
                                    </div>

                                    <div class="container-login100-form-btn">
                                        <button class="login100-form-btn">
                                            Login
                                        </button>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid_3">
                &nbsp;
            </div>

        </div>

    </div>
</section>
<hr>
