
<div class="clearfix"></div>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="clearfix"></div>


    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-bars"></i> Espace client de <small><?= $this->session->get("nom") . ' ' . $this->session->get("prenom") ?></small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="clearfix">&nbsp;</div>
            <div class="x_content">



                <div class="grid_9">
                    <!-- Tab panes -->
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <!--<h2>Glissez et D&eacute;poser les images &agrave; envoyer</h2>-->
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="#">Settings 1</a>
                                                </li>
                                                <li><a href="#">Settings 2</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content" >
                                    <input type="file" name="file" id="file">

                                    <!-- Drag and Drop container-->
                                    <div class="upload-area"  id="uploadfile" style="height: 320px;">
                                    
                                       <h2>Glissez et D&eacute;poser les images &agrave; envoyer</h2><br/>
                                       <h2>où</h2><br/>
                                       <h2>S&eacute;lectionnez les images &agrave; envoyer</h2><br/>
                                    </div>
                                </div>
                              

                            </div>
                        </div>
                        <div class="col-md-11">
                            &nbsp;
                        </div>
                        <div class="col-md-1">
                            <a href="<?= $this->url->get("contributor/") ?>"  class="btn btn-primary">Suivant <i class="fa fa-arrow-right"></i>  </a>
                         
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>

            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
