
<?php

if (!isset($clients)) {
    $clients = [];
}
?>

    
    <div class="col-md-12">
        <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Nom & Prenom</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Pays</th>
                <th>Boite Postal</th>
                <th>Actif</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($clients as $key => $client) {   
            ?>
            <tr>
                <td><?= $client->nom .' '.$client->prenom?></td>
                <td><?= $client->email ?></td>
                <td><?= $client->telephone ?></td>
                <td><?= $client->pays->nompays ?></td>
                <td><?= $client->boitePostale ?></td>
                <td><?= ($client->statut==0)? "Non" : "Oui" ?></td>
            </tr>
            <?php } ?>
            
        </tbody>
        <tfoot>
            <tr>
                <th>Nom & Prenom</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Pays</th>
                <th>Boite Postal</th>
                <th>Actif</th>
            </tr>
        </tfoot>
    </table>
    </div>
