<?php $this->assets->outputCss(); ?>
<section class="wrapper">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Gestions des images</h4>
                
                <div class="container-fuild">
                    <div class="stepwizard">
                        <div class="stepwizard-row setup-panel">
                            <div class="stepwizard-step">
                                <a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
                                <p>Etape 1</p>
                            </div>
                            <div class="stepwizard-step">
                                <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                                <p>Etape 2</p>
                            </div>
                            <div class="stepwizard-step">
                                <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                                <p>Etape 3</p>
                            </div>
                        </div>
                    </div>
                    <form role="form">
                        <div class="row setup-content" id="step-1">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <div class="row">

                                        <h4 class="card-title text-warning text-center">Ajouter l&apos;image</h4>
                                    </div>
                                    <div class="clearfix">&nbsp;</div>
                                    <div class="row">
                                        <div class="col-sm-4 text-center">
                                            <div class="kv-avatar">
                                                <div class="file-loading">
                                                    <input class="avatar-1" name="avatar-1" type="file" required>
                                                </div>
                                            </div>
                                            <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>
                                        </div>
                                        <div class="col-sm-8">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="nom">Nom de l'image<span class="kv-reqd">*</span></label>
                                                        <input type="text" class="form-control" name="nom" required>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="description">Description<span class="kv-reqd">*</span></label>
                                                        <textarea class="form-control" name="description" required></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="keyword">Mot cl&eacute; <span class="kv-reqd">*</span></label>
                                                        <textarea  class="form-control" name="keyword" required></textarea>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="signature">Signature de l'image <span class="kv-reqd">*</span></label>
                                                        <input type="file" class="form-control" name="signature" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="keyword">Categorie de l'image<span class="kv-reqd">*</span></label>
                                                        <select  class="form-control" name="categorie" required>
                                                            <option>beaute</option>
                                                            <option>culture</option>
                                                            <option>voyage</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="signature">Type <span class="kv-reqd">*</span></label>
                                                        <select  class="form-control" name="type" required>
                                                            <option>gratuit</option>
                                                            <option>payant</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                    <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Suivant</button>
                                </div>
                            </div>
                        </div>
                        <div class="row setup-content" id="step-2">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <div class="row">

                                        <h4 class="card-title text-warning text-center">Caract&eacute;ristique de l&apos;image</h4>
                                    </div>
                                    <div class="clearfix">&nbsp;</div>
                                    <div class="row">
                                        <div class="col-sm-3 text-center">
                                            <h5 class="card-title text-warning text-center">Taille grande</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="avatar-2" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>

                                            </div>
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(hauteur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(largeur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-3 text-center">
                                            <h5 class="card-title text-warning text-center">Taille moyenne</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="avatar-2" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>

                                            </div>
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(hauteur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(largeur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-3 text-center">
                                            <h5 class="card-title text-warning text-center">Taille petite</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="avatar-2" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>

                                            </div>
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(hauteur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(largeur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-3 text-center">
                                            <h5 class="card-title text-warning text-center">tr&egrave;s petite</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="avatar-2" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>

                                            </div>
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(hauteur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="carac">Dimension(largeur) <span class="kv-reqd">*</span></label>
                                                        <input type="text"  class="form-control" name="carac[]" required>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>


                                    <!--div class="form-group">
                                        <label class="control-label">Company Address</label>
                                        <input maxlength="200" type="text" required="required" class="form-control" placeholder="Enter Company Address"  />
                                    </div-->
                                    <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Suivant</button>
                                </div>
                            </div>
                        </div>
                        <div class="row setup-content" id="step-3">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <h3> Step 3</h3>
                                    <button class="btn btn-success btn-lg pull-right" type="submit">Finish!</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>



                <!--form class="form-sample">
    
    
                    <div class="row">
                        <div class="col-sm-4 text-center">
                            <div class="kv-avatar">
                                <div class="file-loading">
                                    <input id="avatar-1" name="avatar-1" type="file" required>
                                </div>
                            </div>
                            <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>
                        </div>
                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="nom">Nom de l'image<span class="kv-reqd">*</span></label>
                                        <input type="text" class="form-control" name="nom" required>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="description">Description<span class="kv-reqd">*</span></label>
                                        <textarea class="form-control" name="description" required></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="keyword">Mot cl&eacute; *</label>
                                        <textarea  class="form-control" name="keyword" required></textarea>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="signature">Signature de l'image</label>
                                        <input type="file" class="form-control" name="signature" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="keyword">Categorie de l'image*</label>
                                        <textarea  class="form-control" name="keyword" required></textarea>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="signature">Type</label>
                                        <select  class="form-control" name="type" required>
                                            <option>gratuit</option>
                                            <option>payant</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <hr>
                                <div class="text-right"> 
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </form-->
            </div>
        </div>
    </div>
</section>
<?php $this->assets->outputJs(); ?>
