<?php
$this->assets->outputCss();

if (!isset($access)) {
    $access = [];
}
if (!isset($users)) {
    $users = [];
}

?>
<section class="wrapper">
    <div class="col-12 grid-margin">
        <h4 class="card-title">Gestions des utilisateurs</h4>

        <form method="post" action="<?php $this->url->get("admin/parametre/access"); ?>">
            <div class="row">
                <div class="col-md-push-3 col-md-6 col-md-pull-3">
                    <div class="form-group">
                        <label for="nom">Nom</label>
                        <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom">
                    </div>
                    <div class="form-group">
                        <label for="prenom">Prenom</label>
                        <input type="text" class="form-control" id="prenom" name="prenom" placeholder="Prenom">
                    </div>
                    <div class="form-group">
                        <label for="adresse">Email</label>
                        <input type="email" class="form-control" id="adresse" name="mail" placeholder="Adresse email">
                    </div>
                    <div class="form-group">
                        <label for="login">Login</label>
                        <input type="text" class="form-control" id="login" name="login" placeholder="Identifiant">
                    </div>
                    <div class="form-group">
                        <label for="passwod">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="mot de passe">
                    </div>
                    <div class="form-group">
                        <label for="typeUser">Type Utilisateur</label>
                        <select class="form-control" name="typeUser">
                            <option value="1">utilisateur</option>
                            <option value="0">administrateur</option>
                            <option value="-1">super-admin</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="custom-control custom-checkbox">
                            Actif
                            <input type="checkbox" class="custom-control-input" name="statut" checked='checked' value="1">
                            <span class="custom-control-indicator"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-push-3 col-md-6 col-md-pull-3">
                    <table class="table table-bordered table-definition mb-5">
                        <thead class="table-warning ">
                            <tr>
                                <th>Les droits d&apos;acc&egrave;s</th>

                                <th>Description du droit</th>


                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($access as $key => $value) {

                                ?>
                                <tr>
                                    <td> <label class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" name="access[]" value="<?= $value->id ?>">
                                            <span class="custom-control-indicator"></span>
                                        </label></td>
                                    <td><?= $value->description ?></td>

                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th colspan="4">
                                    <button class="btn btn-primary float-right" type="submit">Enregistrer</button>
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>


        </form>

    </div>

    <div class="clearfix">&nbsp;</div>

    <div class="row">
        <div class="col-md-12">
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Nom & Prenom</th>
                        <th>Email</th>
                        <th>Login</th>
                        <th>Type utilisateur</th>
                        <th>Droit d&apos;acc&egrave;s</th>
                        <th>Date cr&eacute;ation</th>
                        <th>Date modification</th>
                        <th>Statut</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user): ?>
                        <tr>
                            <td><?= $user->nom . '&nbsp;' . $user->prenom; ?></td>
                            <td><?= $user->email ?></td>
                            <td><?= $user->login ?></td>
                            <td>
                                <?php 
                                 if($user->typeUser==1){echo "utilisateur"; }elseif($user->typeUser==0)
                                {echo "administrateur";}elseif($user->typeUser==-1){echo "super-admin";} 
                                ?>
                            </td>
                            <td><?php // $user->login  ?></td>
                            <td><?= $user->dateat ?></td>
                            <td><?= $user->dateup ?></td>
                            <td>
                                <label class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" <?= ($user->statut == 1) ? "checked='checked'" : "" ?> disabled="disabled">
                                    <span class="custom-control-indicator"></span>
                                </label>
                            </td>
                            <td>
                                <a href="#" class="fa fa-pencil-square text-warning"></a>&nbsp;&nbsp;
                                <a href="#" class="fa fa-trash text-danger"></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>


                </tbody>
                <tfoot>
                    <tr>
                        <th>Nom & Prenom</th>
                        <th>Email</th>
                        <th>Login</th>
                        <th>Type utilisateur</th>
                        <th>Droit d&apos;acc&egrave;s</th>
                        <th>Date cr&eacute;ation</th>
                        <th>Date modification</th>
                        <th>Statut</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>


</section>
<?php $this->assets->outputJs(); ?>