 <?php
 $this->assets->outputCss();
if (!isset($clients)) {
    $clients = [];
}
 if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div class="col-md-12 row notification alert fade in alert-dismissable" >
                <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
                <p><?php $this->flashSession->output() ?></p>
            </div>
        <?php endif; ?>

<section class="wrapper">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Gestions des clients</h4>

                <div class="container-fuild">

                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prenom</th>
                                <th>email</th>
                                <th>Telephone</th>
                                <th>Mot de pass</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($clients as $client): ?>
                            <tr>
                               <td><?=  $client->nom ?></td>
                               <td><?=  $client->prenom ?></td>
                               <td><?=  $client->email ?></td>
                               <td><?=  $client->telephone ?></td>
                               <td><?=  $client->password ?></td>
                               <td>
                                   <a href="<?=  $this->url->get("admin/client/update".$client->id); ?>" class="fa fa-pencil-square text-warning"></a>&nbsp;
                                  <a href="<?= $this->url->get("admin/client/delete?AFID=".$client->id); ?>" class="fa fa-trash text-danger"></a>
                               </td>
                                
                            </tr>
                            <?php endforeach; ?>
                            
                        </tbody>
                        
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<?php $this->assets->outputJs(); ?>
