
<div class="col-12 grid-margin">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><b>Listes des abonn&eacute;s</b></h4>
            <form class="form-sample">

                <table id="example" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Reference</th>
                            <th>Nom image</th>
                            <th>Description</th>
                            <th>Prix</th>
                            <th>Infos</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>System Architect</td>
                            <td>Edinburgh</td>
                            <td>61</td>
                            <td>2011/04/25</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Accountant</td>
                            <td>Tokyo</td>
                            <td>63</td>
                            <td>2011/07/25</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Junior Technical Author</td>
                            <td>San Francisco</td>
                            <td>66</td>
                            <td>2009/01/12</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Senior Javascript Developer</td>
                            <td>Edinburgh</td>
                            <td>22</td>
                            <td>2012/03/29</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Accountant</td>
                            <td>Tokyo</td>
                            <td>33</td>
                            <td>2008/11/28</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Integration Specialist</td>
                            <td>New York</td>
                            <td>61</td>
                            <td>2012/12/02</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Sales Assistant</td>
                            <td>San Francisco</td>
                            <td>59</td>
                            <td>2012/08/06</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Integration Specialist</td>
                            <td>Tokyo</td>
                            <td>55</td>
                            <td>2010/10/14</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Javascript Developer</td>
                            <td>San Francisco</td>
                            <td>39</td>
                            <td>2009/09/15</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Software Engineer</td>
                            <td>Edinburgh</td>
                            <td>23</td>
                            <td>2008/12/13</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                             <td><img src="<?= $this->url->getBaseUri() ?>/images/faces/face1.jpg" width="40" height="40" class="img-thumbnail img-responsive"></td>
                            <td>Office Manager</td>
                            <td>London</td>
                            <td>30</td>
                            <td>2008/12/19</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                            <td>Quinn Flynn</td>
                            <td>Support Lead</td>
                            <td>Edinburgh</td>
                            <td>22</td>
                            <td>2013/03/03</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                            <td>Charde Marshall</td>
                            <td>Regional Director</td>
                            <td>San Francisco</td>
                            <td>36</td>
                            <td>2008/10/16</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                            <td>Haley Kennedy</td>
                            <td>Senior Marketing Designer</td>
                            <td>London</td>
                            <td>43</td>
                            <td>2012/12/18</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                            <td>Tatyana Fitzpatrick</td>
                            <td>Regional Director</td>
                            <td>London</td>
                            <td>19</td>
                            <td>2010/03/17</td>
                            <td>$385,750</td><td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                            <td>Michael Silva</td>
                            <td>Marketing Designer</td>
                            <td>London</td>
                            <td>66</td>
                            <td>2012/11/27</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                            <td>Paul Byrd</td>
                            <td>Chief Financial Officer (CFO)</td>
                            <td>New York</td>
                            <td>64</td>
                            <td>2010/06/09</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        <tr>
                            <td>Gloria Little</td>
                            <td>Systems Administrator</td>
                            <td>New York</td>
                            <td>59</td>
                            <td>2009/04/10</td>
                            <td><a href="#"><i class="fa fa-info-circle"></i></a></td>
                        </tr>
                        
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                        </tr>
                    </tfoot>
                </table>
            </form>
        </div>
    </div>
</div>

