$this->assets->outputCss();
<section class="wrapper">

    <div id="accordion">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                       Editer la categorie
                    </button>
                </h5>
            </div>
            
            

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <div>&nbsp;</div>
                    <form class="form-inline" method="post" action="<?= $this->url->get("admin/categorie/update") ?>">
                        <div class="form-group mx-sm-3 mb-2">
                            <label for="categorie" class="sr-only "><i class="fa fa-plus"></i>&nbsp;Cat&eacute;gorie</label>
                            <input type="text" class="form-control" id="categorie" name="categorie" value="<?= $categories->nomCategorie ?>" placeholder="categorie" required="">
                            <input type="hidden" value="<?= $idcategorie ?>" name="idcat"/>
                        </div>
                        <label class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input"  checked='checked' name="statut" value="1">
                            <span class="custom-control-indicator"></span>
                        </label>
                        <button type="submit" class="btn btn-primary mb-2">Enregistrer</button>
                        <a href="<?= $this->url->get("admin/categorie") ?>" class="fa fa-backward btn btn-primary mb-2">&nbsp;Retour</a>
                        
                        
                       
                    </form>
                </div>
            </div>
        </div>
        <!--div class="clearfix">&nbsp;</div-->
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div class="col-md-12 row notification alert fade in alert-dismissable" >
                <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
                <p><?php $this->flashSession->output() ?></p>
            </div>
        <?php endif; ?>
        <div class="clearfix">&nbsp;</div>
        
    </div>
</section>