<?php
if (!isset($clients)) {
    $clients = [];
}
if (!isset($imgEnAttente)) {
    $imgEnAttente = [];
}
if (!isset($imgValide)) {
    $imgValide = [];
}
if (!isset($imgRejete)) {
    $imgRejete = [];
}

?>


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="clearfix"></div>


    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-bars"></i> Espace client de <small>Bintou Jean</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix">&nbsp;</div>
            <div class="col-md-push-11 col-md-1"><a href="<?= $this->url->get("admin/client/contributeur") ?>"><i class="fa fa-backward">&nbsp;Page pr&eacute;cedente</i></a></div>
            <div class="clearfix">&nbsp;</div>
            <div class="x_content">

                <div class="col-xs-3">
                    <!-- required for floating -->
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs tabs-left">
                        <li class="active"><a href="#image_reçu" data-toggle="tab">Images en attente <span class="label label-warning"><?= sizeof($imgEnAttente) ?></span> </a>
                        </li>
                        <li><a href="#profile" data-toggle="tab">Images Valid&eacute;  <span class="label label-success"><?= sizeof($imgValide) ?></span></a>
                        </li>
                        <li><a href="#messages" data-toggle="tab">Images rejet&eacute;e  <span class="label label-danger"><?= sizeof($imgRejete) ?></span></a>
                        </li>
                        <li><a href="#vente" data-toggle="tab">Images Vendues  <span class="label label-info">2</span></a>
                        <li><a href="#gallery" data-toggle="tab">Gallery</a>
                        </li>
                        <li><a href="#facture" data-toggle="tab">Facture</a>
                        </li>
                    </ul>
                </div>

                <div class="col-xs-9">
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <!--bloc d'affichages des images envoye par le contributeur-->
                        <div class="tab-pane active" id="image_reçu">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="x_panel">
                                        <div class="x_title">
                                            <h2>Images Envoy&eacute;es </h2>
                                            <ul class="nav navbar-right panel_toolbox">
                                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                                </li>
                                                <li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#">Settings 1</a>
                                                        </li>
                                                        <li><a href="#">Settings 2</a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                                </li>
                                            </ul>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content">

                                            <form method="post" action="<?= $this->url->get("client/"); ?>">
                                            <div class="row">
                                                <?php if(sizeof($imgEnAttente)>0): ?>
                                                <div class="col-md-4">
                                                    <button class="btn btn-sm btn-success fa fa-check" type="submit" > Valider</button>
<!--                                                </div>
                                                <div class="col-md-2">-->
                                                    <button class="btn btn-sm btn-danger" type="submit" >Rejecter</button>
                                                </div>
                                                <?php endif;?>
                                            </div>
                                            <div class="row">
                                                <?php foreach ($imgEnAttente as $key => $attente) { ?>
                                                    <div class="col-md-55">
                                                        <div class="thumbnail">
                                                            <div class="image view view-first">
                                                                <img style="width: 100px; height: 100px; display: block;" src="<?= $this->url->getBaseUri() . 'public/' . $attente->image ?>" alt="image" />
                                                                <div class="mask">
                                                                    <p><?= $attente->date ?></p>
                                                                    <div class="tools tools-bottom">
                                                                        <a href="#"><i class="fa fa-check"></i></a>
                                                                        <a href="<?= $this->url->getBaseUri() . 'public/' . $attente->image ?>" download="<?= $this->url->getBaseUri() . 'public/' . $attente->image ?>"><i class="fa fa-download"></i></a>
                                                                        <a href="#"><i class="fa fa-times"></i></a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="caption">
                                                                <input type="checkbox" name="valide[]" id="hobby2" value="<?= $attente->id ?>" class="flat" />
                                                                <p><?= $attente->description ?></p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--Image validé -->
                        <div class="tab-pane" id="profile">
                            <div class="row">
                                <?php foreach ($imgValide as $key => $valide) {

                                    ?>
                                    <div class="col-md-55">
                                        <div class="thumbnail">
                                            <div class="image view view-first">
                                                <img style="width: 100%; display: block;" src="<?= $this->url->getBaseUri() . 'public/' . $valide->image ?>" alt="image" />
                                                <div class="mask">
                                                    <p><?= $valide->date ?></p>
                                                    <div class="tools tools-bottom">
                                                        <a href="#"><i class="fa fa-link"></i></a>
                                                        <a href="#"><i class="fa fa-pencil"></i></a>
                                                        <a href="#"><i class="fa fa-times"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="caption">
                                                <input type="checkbox" name="valide[]" id="hobby2" value="run" class="flat" />
                                                <p><?= $valide->description ?></p>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>


                                <!--                                <div class="col-md-55">
                                                                    <div class="thumbnail">
                                                                        <div class="image view view-first">
                                                                            <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                                                                            <div class="mask">
                                                                                <p>Your Text</p>
                                                                                <div class="tools tools-bottom">
                                                                                    <a href="#"><i class="fa fa-link"></i></a>
                                                                                    <a href="#"><i class="fa fa-pencil"></i></a>
                                                                                    <a href="#"><i class="fa fa-times"></i></a>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="caption">
                                                                            <input type="checkbox" name="valide[]" id="hobby2" value="run" class="flat" />
                                                                            <p>Snow and Ice Incoming for the South</p>
                                                                        </div>
                                                                    </div>
                                                                </div>-->
                            </div>
                        </div>



                        <!--Image rejeter-->

                        <div class="tab-pane" id="messages">

                            <div class="row">
                                <?php foreach ($imgRejete as $key => $rejeter) {

                                    ?>
                                    <div class="col-md-55">
                                        <div class="thumbnail">
                                            <div class="image view view-first">
                                                <img style="width: 100%; display: block;" src="<?= $this->url->getBaseUri() . 'public/' . $rejeter->image ?>" alt="image" />
                                                <div class="mask">
                                                    <p><?= $rejeter->date ?></p>
                                                    <div class="tools tools-bottom">
                                                        <a href="#"><i class="fa fa-link"></i></a>
                                                        <a href="#"><i class="fa fa-pencil"></i></a>
                                                        <a href="#"><i class="fa fa-times"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="caption">
                                                <input type="checkbox" name="valide[]" id="hobby2" value="run" class="flat" />
                                                <p><?= $rejeter->description ?></p>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>


                            </div>
                        </div>

                        <!--bloc d'affichage des images vendu-->
                        <div class="tab-pane" id="vente">
                            <div class="col-md-12">
                                <table id="example" class="table table-striped table-bordered" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Image</th>
                                            <th>Prix unitaire</th>
                                            <th>ventes</th>
                                            <th>Pourcentage</th>
                                            <th>Total</th>
                                            <th>Infos</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><img src="#" height="25" class="img img-responsive"></td>
                                            <td>10$</td>
                                            <td>(35)</td>
                                            <td>25%</td>
                                            <td>35000$</td>
                                            <td><a href="#" class="fa fa-info-circle text-info"></a></td>
                                        </tr>
                                        <tr>
                                            <td><img src="#" height="25" class="img img-responsive"></td>
                                            <td>10$</td>
                                            <td>(35)</td>
                                            <td>25%</td>
                                            <td>35000$</td>
                                            <td><a href="#" class="fa fa-info-circle text-info"></a></td>
                                        </tr>
                                        <tr>
                                            <td><img src="#" height="25" class="img img-responsive"></td>
                                            <td>10$</td>
                                            <td>(35)</td>
                                            <td>25%</td>
                                            <td>35000$</td>
                                            <td><a href="#" class="fa fa-info-circle text-info"></a></td>
                                        </tr>



                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Image</th>
                                            <th>Prix unitaire</th>
                                            <th>ventes</th>
                                            <th>Pourcentage</th>
                                            <th>Total</th>
                                            <th>Infos</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>

                        <div class="tab-pane" id="gallery">

                            <div class="col-md-12">
                                <table id="example" class="table table-striped table-bordered" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Images</th>
                                            <th>Description</th>
                                            <th>Mot cle</th>
                                            <th>Date</th>
                                            <th>Prix</th>
                                            <th>Statut</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><img src="#" height="25" class="img img-responsive"></td>
                                            <td>System Architect</td>
                                            <td>Edinburgh, aedqffsfsf, sdfsf, ssf</td>
                                            <td>10-10-2018</td>
                                            <td>420$</td>
                                            <td>valide</td>
                                        </tr>
                                        <tr>
                                            <td><img src="#" height="25" class="img img-responsive"></td>
                                            <td>System Architect</td>
                                            <td>Edinburgh, aedqffsfsf, sdfsf, ssf</td>
                                            <td>10-10-2018</td>
                                            <td>0$</td>
                                            <td>rejeter</td>
                                        </tr>


                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Images</th>
                                            <th>Description</th>
                                            <th>Mot cle</th>
                                            <th>Date</th>
                                            <th>Prix</th>
                                            <th>Statut</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>


                        </div>
                        <div class="tab-pane" id="facture">facture Tab.</div>
                    </div>
                </div>

                <div class="clearfix"></div>

            </div>
        </div>
    </div>
</div>