<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth register-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
              <h2 class="text-center mb-4">R&eacute;cup&eacute;r&eacute; mot de passe</h2>
              <h5 class="text-center mb-4 text-warning small-text">! Vous avez oubli&eacute; votre mot de passe</h5>
            <div class="auto-form-wrapper">
                <form action="#" method="post">
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Nom d&apos;utilisateur ">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                      <input type="email" class="form-control" placeholder="mail de recup&eacute;ration">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                
               
                <div class="form-group">
                    <button class="btn  btn-inverse-warning submit-btn btn-block">R&eacute;initialis&eacute;</button>
                </div>
                
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>