<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
            <div class="auto-form-wrapper">
                <form action="<?= $this->url->get("admin/login"); ?>" method="post">
                <div class="form-group">
                    <label class="label">Nom d&apos;utilisateur</label>
                  <div class="input-group">
                      <input type="text" name="username" class="form-control" placeholder="nom d&apos;utilisateur">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="label">Mot de passe</label>
                  <div class="input-group">
                      <input type="password" name="password" class="form-control" placeholder="*********">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary submit-btn btn-block" type="submit">Connecter</button>
                </div>
                <div class="form-group d-flex justify-content-between">
                  <div class="form-check form-check-flat mt-0">
                    <label class="form-check-label">
                      <input type="checkbox" class="form-check-input" checked> Garder ma session ouverte
                    </label>
                  </div>&nbsp;
                  <a href="session/forgotPass" class="text-small forgot-password text-black">Mot de passe oublier</a>
                </div>
                <div class="form-group">
                  <button class="btn btn-block g-login">
                    <img class="mr-3" src="<?= $this->url->getBaseUri(); ?>public/images/file-icons/icon-google.svg" alt="">Se connecter avec mon compte googles</button>
                </div>
                <!--div class="text-block text-center my-3">
                  <span class="text-small font-weight-semibold">Not a member ?</span>
                  <a href="register.html" class="text-black text-small">Create new account</a>
                </div-->
              </form>
            </div>
            <ul class="auth-footer">
              <li>
                <a href="#">Conditions</a>
              </li>
              <li>
                <a href="#">Aide</a>
              </li>
              <li>
                <a href="#">Termes </a>
              </li>
            </ul>
              <p class="footer-text text-center">copyright © 2018 AfriqueStock. Tout droit r&eacute;server.</p>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>