<?php
$this->assets->outputCss();
if (!isset($categories)) {
    $categories = [];
}
?>
<div class="row">
    <section class="wrapper">

        <div id="accordion">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Ajouter une categorie
                        </button>
                    </h5>
                </div>

                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="card-body">
                        <div>&nbsp;</div>
                        <form class="form-inline" method="post" action="<?= $this->url->get("admin/categorie/") ?>">
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="categorie" class="sr-only "><i class="fa fa-plus"></i>&nbsp;Cat&eacute;gorie</label>
                                <input type="text" class="form-control" id="categorie" name="categorie" placeholder="categorie" required="">
                            </div>
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input"  checked='checked' name="statut" value="1">
                                <span class="custom-control-indicator"></span>
                            </label>
                            <button type="submit" class="btn btn-primary mb-2">Enregistrer</button>
                            <!--input type="hidden" class="form-control" id="parent" name="parent" value="$"-->
                        </form>
                    </div>
                </div>
            </div>
            <!--div class="clearfix">&nbsp;</div-->
            <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
                <div class="col-md-12 row notification alert fade in alert-dismissable" >
                    <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
                    <p><?php $this->flashSession->output() ?></p>
                </div>
            <?php endif; ?>
            
            <div class="clearfix">&nbsp;</div>
            <div class="row">
                <div class="x_content">

                    <div class="table-responsive">
                        <table class="table table-striped jambo_table bulk_action">
                            <thead>
                                <tr class="headings">
                                    <th>
                                        <input type="checkbox" id="check-all" class="flat">
                                    </th>
                                    <th class="column-title">Invoice </th>
                                    <th class="column-title">Cat&eacute;gorie </th>
                                    <th class="column-title">Sous cat&eacute;gorie </th>
                                    <th class="column-title">Voir</th>
                                    <th class="column-title">Date cr&eacute;ation </th>
                                    <th class="column-title">Date modification</th>
                                    <th class="column-title no-link last"><span class="nobr">Action</span>
                                    </th>
                                    <th class="bulk-actions" colspan="7">
                                        <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php
                            foreach ($categories as $key => $categorie):
                                $sousCat = categorie::find(["parent=:val:", "bind" => ["val" => $categorie->idCat]]);
                                ?>
                                <tr class="even pointer">
                                    <td class="a-center ">
                                        <input type="checkbox" class="flat" name="table_records">
                                    </td>
                                    <td scope="row"><?= $key + 1 ?></td>
                                    <td><?= $categorie->nomCategorie ?></td>
                                    <td><?= sizeof($sousCat); ?></td>
                                    <td><a href="<?= $this->url->get("admin/categorie/vue?AFID=" . $categorie->idCat); ?>" class="fa fa-eye text-primary"></a></td>
                                    <td><?= $categorie->dateat ?></td>
                                    <td><?= $categorie->dateup ?></td>
                                    <td>
                                        <a href="<?= $this->url->get("admin/categorie/update?AFID=" . $categorie->idCat); ?>" class="fa fa-pencil-square text-warning"></a>&nbsp;
                                        <a href="<?= $this->url->get("admin/categorie/delete?AFID=" . $categorie->idCat); ?>" class="fa fa-trash text-danger"></a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>
        </div>
    </section>
</div>