<?php 
  $this->assets->outputCss(); 
  if (!isset($types)) {
    $types = [];
}
?>
<section class="wrapper">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Gestion des types</h4>

                
                    <div>&nbsp;</div>
                     <div class="col-md-12">
                    <form role="form" method="post" action="<?php $this->url->get("admin/type/newType") ?>">             
                                <div class="col-xs-12">
                                    <div class="row">
                                        <h4 class="card-title text-warning text-center">Ajouter le type</h4>
                                    </div>
                                    <div class="clearfix">&nbsp;</div>
                                    <div class="row">
                                        
                                        <div class="col-sm-8">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="libelletype">Libelle du type<span class="kv-reqd">*</span></label>
                                                        <input type="text" class="form-control" name="libelletype" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="description">Description<span class="kv-reqd">*</span></label>
                                                        <textarea class="form-control" name="description" required></textarea>
                                                    </div>
                                                </div>                                                                                       
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <button class="btn btn-info btn-sm pull-right" type="submit" >Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>   
</section>
<?php $this->assets->outputJs(); 

