<div class="col-12 grid-margin">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><b>Creation d&apos;un nouveau utilisateur</b></h4>
            <form class="form-sample">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Nom</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" name="nom" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Prenom</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" name="prenom"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">E-mail</label>
                            <div class="col-sm-9">
                                <input type="email" class="form-control" name="email"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Login</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" name="login"/>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Mot de passe</label>
                            <div class="col-sm-9">
                                <input type="password" class="form-control" name="password"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Confirmer </label>
                            <div class="col-sm-9">
                                <input type="password" class="form-control" name="confirmPass"/>
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
<div class="clearfix">&nbsp;</div>
<div class="col-12 grid-margin">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><b>Droits d'acc&egrave;s de l'utilisateur</b></h4>
            <form class="form-sample">
                <div class="row">
                    
                    <div class="col-md-3">
                        <div class="form-group row">
                            <div class="form-radio">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" name="membershipRadios" id="membershipRadios2" value=""> ajout
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group row">
                            <div class="form-radio">
                                <label class="form-check-label">
                                    <input type="checkbox" checked="checked" class="form-check-input" name="membershipRadios" id="membershipRadios2" value=""> modification
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group row">
                            <div class="form-radio">
                                <label class="form-check-label">
                                    <input type="checkbox" checked="checked" class="form-check-input" name="membershipRadios" id="membershipRadios2" value=""> suppression
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group row">
                            <div class="form-radio">
                                <label class="form-check-label">
                                    <input type="checkbox" checked="checked" class="form-check-input" name="membershipRadios" id="membershipRadios2" value=""> Param&egrave;tre
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group row">
                            <div class="form-radio">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" name="membershipRadios" id="membershipRadios2" value=""> utilisateur
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group row">
                            <div class="form-radio">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" name="membershipRadios" id="membershipRadios2" value=""> profile
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
           
            </form>
        </div>
    </div>
</div>

