<?php 
  $this->assets->outputCss(); 
  if (!isset($categories)) {
    $categories = [];
}
?>
<section class="wrapper">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Gestions des images</h4>

                <div class="container-fuild">
                    <div class="stepwizard">
                        <div class="stepwizard-row setup-panel">
                            <div class="stepwizard-step">
                                <a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
                                <p>Etape 1</p>
                            </div>
                            <div class="stepwizard-step">
                                <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                                <p>Etape 2</p>
                            </div>
                            <div class="stepwizard-step">
                                <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                                <p>Etape 3</p>
                            </div>
                        </div>
                    </div>
                    <div>&nbsp;</div>
                    <form role="form" method="post" action="<?php $this->url->get("admin/image/newPicture") ?>" enctype="multipart/form-data">
                        <div class="row setup-content" id="step-1">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <h4 class="card-title text-warning text-center">Ajouter l&apos;image</h4>
                                    </div>
                                    <div class="clearfix">&nbsp;</div>
                                    <div class="row">
                                        <div class="col-sm-4 text-center">
                                            <div class="kv-avatar">
                                                <div class="file-loading">
                                                    <input class="avatar-1" name="signature" type="file" name="taille[]" required>
                                                </div>
                                            </div>
                                            <div class="kv-avatar-hint"><small>Image en filigrame</small></div>
                                        </div>
                                        <div class="col-sm-8">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="nom">Nom de l'image<span class="kv-reqd">*</span></label>
                                                        <input type="text" class="form-control" name="nom" required>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="description">Description<span class="kv-reqd">*</span></label>
                                                        <textarea class="form-control" name="description" required></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label for="keyword">Mot cl&eacute; <span class="kv-reqd">*</span></label>
                                                        <textarea  class="form-control" name="motcle" required></textarea>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6">

                                                    <div class="form-group">
                                                        <label for="keyword">Categorie de l'image<span class="kv-reqd">*</span></label>
                                                        <select  class="form-control" name="categorie" required>
                                                            <?php foreach($categories as $categorie): ?>
                                                            <option value="<?= $categorie->id ?>"><?= $categorie->nomCategorie ?></option>
                                                            <?php endforeach; ?>
                                                            <!--option>culture</option>
                                                            <option>voyage</option-->
                                                        </select>
                                                    </div>


                                                </div>
                                            </div>
                                           
                                        </div>
                                    </div>
                                    <button class="btn btn-warning nextBtn btn-sm pull-right" type="button" >Suivant</button>
                                </div>
                            </div>
                        </div>
                        <div class="row setup-content" id="step-2">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <!--div class="row">
                                        <h4 class="card-title text-warning text-center">Image normale</h4>
                                    </div-->
                                    <div class="clearfix">&nbsp;</div>
                                    <div class="row">
                                        <div class="col-sm-4 text-center">
                                            <h5 class="card-title text-warning text-center">Taille grande</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="taille[]" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Image normale (5047 * 3045)</small></div>

                                            </div>
                                           
                                        </div>
                                        <div class="col-sm-4 text-center">
                                            <h5 class="card-title text-warning text-center">Taille moyenne</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="taille[]" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Image normale (5047 * 3045)</small></div>
                                            </div>
                                            
                                        </div>
                                        <div class="col-sm-4 text-center ">
                                            <h5 class="card-title text-warning text-center">Taille petite</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="taille[]" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>

                                            </div>
                                            
                                        </div>
                                        <!--div class="col-sm-3 text-center">
                                            <h5 class="card-title text-warning text-center">tr&egrave;s petite</h5>
                                            <div class="form-group">
                                                <div class="kv-avatar">
                                                    <div class="file-loading">
                                                        <input class="avatar-1" name="taille[]" type="file" required>
                                                    </div>
                                                </div>
                                                <div class="kv-avatar-hint"><small>Select file < 1500 KB</small></div>
                                            </div>
                                            
                                        </div-->

                                    </div>

                                    <button class="btn btn-warning nextBtn btn-sm pull-right" type="button" >Suivant</button>
                                </div>
                            </div>
                        </div>
                        <div class="row setup-content" id="step-3">
                            <div class="col-md-12">
                                <div class="col-xs-12">
                                    <!--h3> Step 3</h3-->
                                    <div class="row">
                                        <div class="col-md-push-3 col-md-6 col-md-pull-3">
                                            <div class="form-group">
                                                <label for="nom">photographe</label>
                                                <select class="form-control" name="photographe">
                                                    <option value="1">robert</option>
                                                    <option value="2">moli</option>
                                                </select>
                                            </div>
                                          

                                            <div class="form-group">
                                                <label for="nom">Type</label>
                                                <select class="form-control" name="type">
                                                    <option>Gratuit</option>
                                                    <option>Payant</option>
                                                </select>
                                            </div>

                                            <div class="form-group">
                                                <label for="prix">Prix en ($)</label>
                                                <input type="number" class="form-control" min="5" id="login" name="prix" placeholder="Price">
                                            </div>
                                            <div class="form-group">
                                                <label class="custom-control custom-checkbox">
                                                    Actif
                                                    <input type="checkbox" class="custom-control-input" name="statut" checked='checked' value="1">
                                                    <span class="custom-control-indicator"></span>
                                                </label>
                                            </div>
                                            <div class="col-md-12">
                                                <button class="btn btn-success btn-sm pull-right" type="submit">Enregistrer</button>
                                            </div>
                                        </div>
                                    </div>
                                    <!--button class="btn btn-success btn-sm pull-right" type="submit">Enregistrer</button-->
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php $this->assets->outputJs(); ?>

