<?php
if (!isset($photographes)) {
    $photographes = [];
}
if (!isset($images)) {
    $images = [];
}
?>
<div class="row">
    <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
        <div class="col-md-12 row notification alert fade in alert-dismissable" >
            <a href="#" class="close" data-dismiss="alert" arial-label="close" titre="close">x</a>
            <p><?php $this->flashSession->output() ?></p>
        </div>
    <?php endif; ?>
    <div class="clearfix">&nbsp;</div>
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Form Wizards</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Form Wizards <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <form method="post" action="<?= $this->url->get("admin/image/upPicture") ?>" enctype="multipart/form-data">
                        <div class="x_content">


                            <!-- Smart Wizard -->
                            <p>This is a basic form wizard example that inherits the colors from the selected scheme.</p>
                            <div id="wizard" class="form_wizard wizard_horizontal">
                                <ul class="wizard_steps">
                                    <li>
                                        <a href="#step-1">
                                            <span class="step_no">1</span>
                                            <span class="step_descr">
                                                Step 1<br />
                                                <small>Etape1 Information</small>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#step-2">
                                            <span class="step_no">2</span>
                                            <span class="step_descr">
                                                Step 2<br />
                                                <small>Etape2 chargement d'images</small>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#step-3">
                                            <span class="step_no">3</span>
                                            <span class="step_descr">
                                                Step 3<br />
                                                <small>Etape3 prix</small>
                                            </span>
                                        </a>
                                    </li>

                                </ul>

                                <div id="step-1">
                                    <div class="col-md-12">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <h4 class="card-title text-warning text-center">Ajouter l&apos;image</h4>
                                            </div>
                                            <div class="clearfix">&nbsp;</div>
                                            <div class="row">
                                                <div class="col-sm-push-1 col-sm-5 text-center">
                                                    <div class="kv-avatar">
                                                        <div>
                                                            <img width="45" src="<?= $this->url->getBaseUri() . "public/images/photo/" . $image->signature ?>">
                                                        </div>
                                                        <div class="clearfix">&nbsp;</div>
                                                        <div class="file-loading">
                                                            <input class="form-control file-input"  type="file" name="taille[]" >
                                                        </div>
                                                    </div>
                                                    <div class="kv-avatar-hint"><small>Image en filigrame</small></div>
                                                </div>
                                                <div class="col-sm-push-1 col-sm-5 text-center">
                                                    <div class="kv-avatar">
                                                        <div>
                                                            <img width="45"  src="<?= $this->url->getBaseUri() . "public/images/photo/" . $image->affiche ?>">
                                                        </div>
                                                        <div class="clearfix">&nbsp;</div>
                                                        <div class="file-loading">
                                                            <input class="form-control file-input"  type="file" name="taille[]" >
                                                        </div>
                                                    </div>
                                                    <div class="kv-avatar-hint"><small>Image a affich&eacute;</small></div>
                                                </div>
                                                <div class="clearfix">&nbsp;</div>
                                                <div class="clearfix">&nbsp;</div>
                                                <div class="clearfix">&nbsp;</div>
                                                <div class="col-sm-push-1 col-sm-10 col-sm-pull-1">
                                                    <div class="row">
                                                        <div class="col-sm-6">
                                                            <div class="form-group">
                                                                <label for="nom">Nom de l'image<span class="kv-reqd">*</span></label>
                                                                <input type="text" class="form-control" value="<?= $image->nom ?>" name="nom" >
                                                            </div>
                                                        </div>
                                                        <div class="col-sm-6">

                                                            <div class="form-group">
                                                                <label for="keyword">Categorie de l'image<span class="kv-reqd">*</span></label>
                                                                <select  class="form-control" name="categorie">
                                                                    <?php foreach ($categories as $categorie): ?>
                                                                        <option value="<?= $categorie->idCat ?>" <?= ($image->idcategorie == $categorie->idCat) ? "selected" : "" ?>><?= $categorie->nomCategorie ?></option>
                                                                    <?php endforeach; ?>
                                                                </select>
                                                            </div>


                                                        </div>
                                                    </div>
                                                    <div class="row">

                                                        <div class="col-sm-6">
                                                            <div class="form-group">
                                                                <label for="keyword">Mot cl&eacute; <span class="kv-reqd">*</span></label>
                                                                <textarea  class="form-control" name="motcle"><?= $image->motcle ?></textarea>
                                                            </div>
                                                        </div>
                                                        <div class="col-sm-6">
                                                            <div class="form-group">
                                                                <label for="description">Description<span class="kv-reqd">*</span></label>
                                                                <textarea class="form-control" name="description" ><?= $image->description ?></textarea>
                                                            </div>
                                                        </div>
                                                    </div>


                                                </div>
                                            </div>
                                            <!--<button class="btn btn-warning nextBtn btn-sm pull-right" type="button" >Suivant</button>-->
                                        </div>
                                    </div>


                                </div>
                                <div id="step-2">
                                    <h2 class="StepTitle">Chargement des images</h2><br>
                                    <div class="col-md-12">

                                        <div class="col-md-4">
                                            <div>
                                                <img width="45" src="<?= $this->url->getBaseUri() . "public/images/photo/" . $image->affiche ?>">
                                            </div>
                                            <div class="clearfix">&nbsp;</div>
                                            <?php 
                                            foreach ($images as $value): 
                                                if($value->taille=="grande"):
                                                ?>
                                                <div>
                                                    <?= $value->width . "px | " . $value->height . "px" ?>
                                                </div>
                                            <?php endif; endforeach; ?>
                                            <div class="clearfix">&nbsp;</div>
                                            <input type="file" name="taille[]" class="form-control file-input">
                                            <p>grande image</p>
                                        </div>

                                        <div class="col-md-4">
                                            <div>
                                                <img width="45"  src="<?= $this->url->getBaseUri() . "public/images/photo/" . $image->affiche ?>">
                                            </div>
                                            <div class="clearfix">&nbsp;</div>
                                            <?php 
                                            foreach ($images as $value): 
                                                if($value->taille=="moyenne"):
                                                ?>
                                                <div>
                                                    <?= $value->width . "px | " . $value->height . "px" ?>
                                                </div>
                                            <?php endif; endforeach; ?>
                                            <div class="clearfix">&nbsp;</div>
                                            <input type="file" name="taille[]"  class="form-control file-input">
                                            <p>image moyenne</p>
                                        </div>
                                        <div class="col-md-4">
                                            <div>
                                                <img width="45"  src="<?= $this->url->getBaseUri() . "public/images/photo/" . $image->affiche ?>">
                                            </div>
                                            <div class="clearfix">&nbsp;</div>
                                            <?php 
                                            foreach ($images as $value): 
                                                if($value->taille=="petite"):
                                                ?>
                                                <div>
                                                    <?= $value->width . "px | " . $value->height . "px" ?>
                                                </div>
                                            <?php endif; endforeach; ?>
                                            <div class="clearfix">&nbsp;</div>
                                            <input type="file" name="taille[]" class="form-control file-input">
                                            <p>image petite</p>
                                        </div>

                                    </div>
                                </div>
                                <div id="step-3">
                                    <h2 class="StepTitle">Etape3 prix  </h2>
                                    <div class="row">
                                        <div class="col-md-push-3 col-md-6 col-md-pull-3">
                                            <div class="form-group">
                                                <label for="nom">photographe</label>
                                                <select class="form-control" name="photographe">
                                                    <?php foreach ($photographes as $key => $photographe) {
                                                        ?>
                                                        <option value="<?= $photographe->id ?>" <?= ($image->photographe == $photographe->id) ? "selected" : "" ?>><?= $photographe->nom . ' ' . $photographe->prenom ?></option>
                                                    <?php } ?>

                                                </select>
                                            </div>

                                            <div class="form-group">
                                                <label for="nom">Type</label>
                                                <select class="form-control" name="type">
                                                    <option>Gratuit</option>
                                                    <option>Payant</option>
                                                </select>
                                            </div>

                                            <div class="form-group">
                                                <label for="prix">Grand Prix en ($)</label>
                                                <input type="number" value="<?= $image->prixG ?>"  readonly="yes" class="form-control" min="5" id="login" name="prixG" placeholder="Prix grande">
                                            </div>

                                            <div class="form-group">
                                                <label for="prix">Moyen Prix en ($)</label>
                                                <input type="number" value="<?= $image->prixM ?>"  readonly="yes" class="form-control" min="5" id="login" name="prixM"  placeholder="Prix moyenne">
                                            </div>

                                            <div class="form-group">
                                                <label for="prix">Petit Prix en ($)</label>
                                                <input type="number" value="<?= $image->prixP ?>"  readonly="yes" class="form-control" min="5" id="login" name="prixP" placeholder="Prix petite">
                                            </div>

                                            <div class="form-group">
                                                <label class="custom-control custom-checkbox">
                                                    Actif
                                                    <input type="checkbox" class="custom-control-input" name="statut" checked='checked' value="1">
                                                    <span class="custom-control-indicator"></span>
                                                </label>
                                            </div>
                                            <div class="col-md-12">
                                                <input type="hidden" name="identifiant" value="<?= $image->idimage ?>">
                                                <button class="btn btn-success btn-sm pull-right" type="submit">Enregistrer</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>