
<div class="col-12 grid-margin">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><b>Gestions des utilisateurs</b></h4>
            <form class="form-sample">

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nom</th>
                            <th scope="col">Prenom</th>
                            <th scope="col">login</th>
                            <th scope="col">email</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>mdero</td>
                            <td>@mdo</td>
                            <td>
                                <a href="#"><i class="fa fa-pencil-square"></i></a>&nbsp;
                                <a href="#"><i class="fa fa-trash-o"></i></a>
                            </td>
                            
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Jacob</td>
                            <td>Thornton</td>
                            <td>mdero</td>
                            <td>@mdo</td>
                            <td>
                                <a href="#"><i class="fa fa-pencil-square"></i></a>&nbsp;
                                <a href="#"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Larry</td>
                            <td>the Bird</td>
                            <td>mdero</td>
                            <td>@mdo</td>
                            <td>
                                <a href="#"><i class="fa fa-pencil-square"></i></a>&nbsp;
                                <a href="#"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>

